
import { HealthPackage, LabMachine } from './types';

export const HEALTH_PACKAGES: HealthPackage[] = [
  {
    name: 'Maha Aaro Screen',
    totalTests: 55,
    price: 999,
    discountedPrice: 799,
    categories: [
      { name: 'Diabetic Screen', details: 'Fasting Bl. Sugar' },
      { name: 'Blood Profile (CBC)', details: '23 Tests' },
      { name: 'Heart Health-Lipid Profile', details: '7 Tests' },
      { name: 'Liver Profiles', details: '1 Test' },
      { name: 'Kidney Profile', details: '1 Test' },
      { name: 'Electrolytes Profile', details: '5 Tests' },
      { name: 'Urine Analysis', details: 'Includes 16 Tests' },
      { name: 'Thyroid Profile', details: '1 test' },
    ],
  },
  {
    name: 'Maha Aaro Basic Screen',
    totalTests: 70,
    price: 1499,
    discountedPrice: 1199,
    categories: [
      { name: 'Diabetic Screen', details: 'Fasting Bl. Sugar' },
      { name: 'Blood Profile (CBC)', details: '23 Tests' },
      { name: 'Heart Health-Lipid Profile', details: '7 Tests' },
      { name: 'Liver Profiles', details: '10 Tests' },
      { name: 'Kidney Profile', details: '7 Tests' },
      { name: 'Electrolytes Profile', details: '5 Tests' },
      { name: 'Urine Analysis', details: 'Includes 16 Tests' },
      { name: 'Thyroid Profile', details: '1 test' },
    ],
  },
  {
    name: 'Maha Aaro Basic',
    totalTests: 72,
    price: 1799,
    discountedPrice: 1499,
    categories: [
      { name: 'Diabetic Screen', details: 'Fasting Bl. Sugar' },
      { name: 'Blood Profile (CBC)', details: '23 Tests' },
      { name: 'Heart Health-Lipid Profile', details: '7 Tests' },
      { name: 'Liver Profiles', details: '10 Tests' },
      { name: 'Kidney Profile', details: '7 Tests' },
      { name: 'Thyroid Profile', details: '3 Tests' },
      { name: 'Electrolytes Profile', details: '5 Tests' },
      { name: 'Urine Analysis', details: '16 Tests' },
    ],
  },
  {
    name: 'Maha Aaro Basic Plus Profile',
    totalTests: 73,
    price: 2499,
    discountedPrice: 1999,
    isFeatured: true,
    categories: [
      { name: 'HbA1c', details: 'Sugar Memory' },
      { name: 'Diabetic Screen', details: 'Fasting Bl. Sugar' },
      { name: 'Blood Profile (CBC)', details: '23 Tests' },
      { name: 'Heart Health-Lipid Profile', details: '7 Tests' },
      { name: 'Liver Profiles', details: '10 Tests' },
      { name: 'Kidney Profile', details: '7 Tests' },
      { name: 'Thyroid Profile', details: '3 Tests' },
      { name: 'Electrolytes Profile', details: '5 Tests' },
      { name: 'Urine Analysis', details: '16 Tests' },
    ],
  },
  {
    name: 'Maha Aaro Health Profile',
    totalTests: 78,
    price: 3499,
    discountedPrice: 2999,
    categories: [
      { name: 'Vitamin D', details: 'Evaluates Bone Health' },
      { name: 'Vitamin B12', details: 'Eval. Nerve Damage' },
      { name: 'Iron Profile', details: '3 Tests' },
      { name: 'HbA1c', details: 'Sugar Memory' },
      { name: 'Diabetic Screen', details: 'Fasting Blood Sugar' },
      { name: 'Blood Profile (CBC)', details: '23 Tests' },
      { name: 'Heart Health-Lipid Profile', details: '7 Tests' },
      { name: 'Liver Profiles', details: '10 Tests' },
      { name: 'Kidney Profile', details: '7 Tests' },
      { name: 'Thyroid Profile', details: '3 Tests' },
      { name: 'Electrolytes Profile', details: '5 Tests' },
      { name: 'Urine Analysis', details: '16 Tests' },
    ],
  },
    {
    name: 'Maha Aaro Male Profile',
    totalTests: 80,
    price: 3999,
    discountedPrice: 3499,
    categories: [
        { name: 'Vitamin D', details: 'Evaluates Bone Health' },
        { name: 'Vitamin B12', details: 'Eval. Nerve Damage' },
        { name: 'Iron Profile', details: '3 Tests' },
        { name: 'Cancer maker', details: 'PSA' },
        { name: 'HbA1c', details: 'Sugar Memory' },
        { name: 'Diabetic Screen', details: 'Fasting Blood Sugar' },
        { name: 'Blood Profile (CBC)', details: '23 Tests' },
        { name: 'Heart Health-Lipid Profile', details: '7 Tests + Homosystein' },
        { name: 'Liver Profiles', details: '10 Tests' },
        { name: 'Kidney Profile', details: '7 Tests' },
        { name: 'Thyroid Profile', details: '3 Tests' },
        { name: 'Electrolytes Profile', details: '5 Tests' },
        { name: 'Urine Analysis', details: 'Includes 16 Tests' },
    ],
  },
  {
    name: 'Maha Aaro Female Profile',
    totalTests: 80,
    price: 3999,
    discountedPrice: 3499,
    categories: [
        { name: 'Vitamin D', details: 'Evaluates Bone Health' },
        { name: 'Vitamin B12', details: 'Evaluates Nerve Damage' },
        { name: 'Iron Profile', details: '3 Tests' },
        { name: 'Cancer Maker', details: 'CA-125' },
        { name: 'HbA1c', details: 'Sugar Memory' },
        { name: 'Diabetic Screen', details: 'Fasting Blood Sugar' },
        { name: 'Blood Profile (CBC)', details: '23 Tests' },
        { name: 'Heart Health-Lipid Profile', details: '7 Tests + Homosystein' },
        { name: 'Liver Profiles', details: '10 Tests' },
        { name: 'Kidney Profile', details: '7 Tests' },
        { name: 'Thyroid Profile', details: '3 Tests' },
        { name: 'Electrolytes Profile', details: '5 Tests' },
        { name: 'Urine Analysis', details: '16 Tests' },
    ],
  },
];

export const LAB_MACHINES: LabMachine[] = [
    { name: 'BC-5380', model: 'BC-5380', type: 'Fully Auto Blood Cell Counter', features: ['Internal Bar Code Reader'], testsPerHour: '60 tests', imageUrl: './public/mach1.png' },
    { name: 'BC-5130', model: 'BC-5130', type: 'Fully Auto Blood Cell Counter', features: ['External Bar Code Reader'], testsPerHour: '60 tests', imageUrl: './public/mach2.png' },
    { name: 'AFT-800D', model: 'AFT-800D', type: 'Fully Auto Electrolyte Analyzer', features: ['External Bar Code Reader'], testsPerHour: '60 tests', imageUrl: './public/mach3.png' },
    { name: 'BS-240', model: 'BS-240', type: 'Fully Auto Biochemistry Analyzer', features: ['Internal Bar Code Reader'], testsPerHour: '200 tests', imageUrl: './public/mach4.png' },
    { name: 'BA-88', model: 'BA-88', type: 'Semi Automatic Biochemistry Analyzer', features: [], testsPerHour: '50 tests', imageUrl: './public/mach5.png' },
    { name: 'Centaur-XP', model: 'Centaur-XP', type: 'Automatic Immunoassay Analyser', features: ['All types of Hormones', 'Cancer marker', 'Infections like HIV and Hepatitis', 'Infertility profile', 'Vitamins A, B, C, D, E'], testsPerHour: '200 tests/hr', imageUrl: './public/mach.png' },
];