import type { Test } from './types';

export const RATE_LIST: Test[] = [
  { name: 'GLUCOSE TOLERANCE TEST (GTT), 2 SAMPLES', code: '00009', amount: 120 },
  { name: '17 HYDROXY-PROGESTERONE, SERUM by CLIA', code: 'SL17H', amount: 2000 },
  { name: '24 HRS URINE AFB REPORT', code: 'SL24A', amount: 700 },
  { name: '24 hrs Urine V.M.A.', code: 'SLVMA', amount: 2200 },
  { name: '25 - HYDROXYVITAMIN D (VITAMIN D TOTAL), SERUM', code: 'SLVID', amount: 1800 },
  { name: '3D OVULATION MONITORING WITH AVC', code: 'avc11', amount: 1000 },
  { name: '3D PELVIC/GYNAECOLOGICAL SCAN', code: '4D111', amount: 1000 },
  { name: '3D SALINE HYSTEROSALPINGOSONOGRAM', code: 'SH111', amount: 1000 },
  { name: '3D TVS', code: '23148', amount: 1000 },
  { name: '4D FETAL ANOMALY SCAN (LEVEL II SCAN)', code: '98523', amount: 1000 },
  { name: '4D FETAL ANOMALY SCAN (TWIN PREGNANCY)', code: '4DTWP', amount: 1000 },
  { name: '4D FETAL CARDIOGRAPHY', code: '12457', amount: 1000 },
  { name: '4D FOLLICULAR MONITORING', code: '98456', amount: 1000 },
  { name: '4D HD LIVE BABY SCAN', code: '52141', amount: 1000 },
  { name: '4D NUCHAL TRANSLUCENCY(NT) SCAN', code: '47512', amount: 1000 },
  { name: '4D VIABILITY SCAN', code: '17590', amount: 1000 },
  { name: 'ABO GROUP & RH TYPE, (BLOOD GROUP)', code: 'SLBLG', amount: 100 },
  { name: 'ABS EOSINOPHIL COUNT (AEC), EDTA WHOLE BLOOD', code: 'ALAEC', amount: 200 },
  { name: 'ACE-Angiotensin Conv. Enzyme, by FAPGG Hydrolysis', code: 'SLACE', amount: 2000 },
  { name: 'acetylcholine receptor AB', code: 'ghklm', amount: 4500 },
  { name: 'ACID FAST BACILLI (AFB) SMEAR', code: 'afbss', amount: 700 },
  { name: 'ACID FAST BACILLI (AFB) SMEAR', code: 'SLAFI', amount: 700 },
  { name: 'ACTH-Adreno corticotropic hormone (plasma)', code: 'ALACT', amount: 2500 },
  { name: 'ACTIVATED PARTIAL THROMBOPLASTIN TIME (APTT)', code: 'SLAPT', amount: 500 },
  { name: 'ADENOSINE DEAMINASE (ADA), FLUID/SERUM', code: 'SLADA', amount: 1000 },
  { name: 'AFB (mycobacterial) culture', code: 'SLMYC', amount: 2500 },
  { name: 'AFB (MYCOBACTERIAL) DRUG 1 & 2nd line', code: 'SLA12', amount: 4500 },
  { name: 'AFB / ZN STAIN SPUTUM', code: 'SLSPU', amount: 700 },
  { name: 'AFB C/S', code: 'SLAFC', amount: 4500 },
  { name: 'AFB Culture', code: 'alafb', amount: 2500 },
  { name: 'AFB CULTURE BY BACTEC METHOD', code: 'SLBA1', amount: 1000 },
  { name: 'AFB Sensitivity - 1st & 2nd line drugs', code: 'SLAF2', amount: 1000 },
  { name: 'ALANINE AMINOTRANSFERASE (ALT/SGPT), SERUM', code: 'SLSGT', amount: 200 },
  { name: 'ALBUMIN, SERUM', code: 'SLAL1', amount: 300 },
  { name: 'ALCOHOL (ETHANOL), SERUM', code: 'alcoe', amount: 1500 },
  { name: 'ALDESTERON 24 HR URINE', code: 'SLA24', amount: 1000 },
  { name: 'Alfa Feto Protein(AFP)', code: 'SLAFP', amount: 1500 },
  { name: 'ALKALINE PHOSPHATASE, SERUM', code: 'SLALA', amount: 200 },
  { name: 'Alpha Feto Protein ( AFP ), serum by CMIA', code: 'alafp', amount: 1500 },
  { name: 'AMH (ANTI-MULLERIAN HORMONE)', code: 'SLAMH', amount: 2400 },
  { name: 'Amino Acids', code: 'SLAMN', amount: 1000 },
  { name: 'AMMONIA', code: 'SLAMM', amount: 1200 },
  { name: 'AMYLASE, SERUM', code: 'SLAMY', amount: 700 },
  { name: 'ANA -Anti Nuclear Antibody by IF', code: 'SLANI', amount: 2500 },
  { name: 'ANA BLOT ASSAY', code: 'SLABA', amount: 4000 },
  { name: 'ANA-Anti Nulclear Antibody, serum by EIA', code: 'ALANE', amount: 2000 },
  { name: 'Anaerobic Culture & Sensitivity', code: 'alano', amount: 1000 },
  { name: 'ANCA-MPO (p-ANCA), serum by EIA', code: 'alacc', amount: 1200 },
  { name: 'ANCA-PR3 (c-ANCA), serum by EIA', code: 'alanc', amount: 1200 },
  { name: 'ANDROGEN LEVEL', code: 'SLAND', amount: 1000 },
  { name: 'ANOMALY SCAN (LEVEL II SCAN)', code: 'IISCA', amount: 1000 },
  { name: 'ANTI HEPATITIS REPORT', code: 'SLHA1', amount: 2000 },
  { name: 'ANTI NUCLEAR ANTIBODY IMMUNOFLUORESCENCE ASSAY.', code: 'SLANC', amount: 2500 },
  { name: 'ANTI PR3 & MPO', code: 'SLPR3', amount: 1000 },
  { name: 'Anti Beta-2- Glycoprotein I-IgG Ab and IgM Ab, Serum', code: 'algly', amount: 2500 },
  { name: 'ANTI CCP (CYCLIC CITRULLNATED PEPTIDE)', code: 'SLCCP', amount: 1700 },
  { name: 'ANTI DS-DNA', code: 'SLDN1', amount: 1200 },
  { name: 'ANTI DS-DNA ANTIBODY IFA', code: 'SLDSF', amount: 1500 },
  { name: 'Anti GAD Antibody', code: 'asdad', amount: 4500 },
  { name: 'ANTI HEPATITIS A REPORT', code: 'SLHAV', amount: 2000 },
  { name: 'Anti HEPATITIS B core IgM Antibody', code: 'SLHBC', amount: 1000 },
  { name: 'ANTI HEPATITIS E REPORT', code: 'SLHEV', amount: 1000 },
  { name: 'ANTI INTRINSIC FACTOR ANTIBODY BY IF', code: 'SLIFA', amount: 1000 },
  { name: 'ANTI MICROSOMAL ANTIBODIES ( M/TPO)', code: 'SLANT', amount: 1200 },
  { name: 'ANTI MITOCHONDRIAL ANTIBODIES', code: 'SLAMR', amount: 2000 },
  { name: 'Anti Parietal cells Antibody', code: 'bbvvv', amount: 3000 },
  { name: 'Anti Phospholipid Antibody', code: 'APLAa', amount: 2500 },
  { name: 'Anti Smooth Muscle Antibody ( ASMA ) by IF', code: 'SLASM', amount: 3000 },
  { name: 'ANTI SPERM ANTIBODY', code: 'SLASP', amount: 2500 },
  { name: 'ANTI THROMBIN III ACTIVITY (FUNCTIONAL)', code: 'SLATT', amount: 1000 },
  { name: 'ANTI THYROGLOBULIN ANTIBODY (ATG)', code: 'SLAN2', amount: 2000 },
  { name: 'ANTICARDIOLIPIN ANTIBODY (ACA) REPORT', code: 'SLACP', amount: 2000 },
  { name: 'ANTINEUTROPHIL CYTOPLASMIC ANTIBODIES(P-ANCA + C-ANCA)', code: 'SLAPA', amount: 2500 },
  { name: 'ANTI-NUCLEAR AB-IFA,HEP2 SERUM', code: 'ALANR', amount: 1220 },
  { name: 'ANTINUCLEAR ANTIBODY REPORT', code: 'SLANA', amount: 1200 },
  { name: 'ANTI-PHOSPHOLIPID ANTIBODIES (IgG & IgM)', code: 'SLAPL', amount: 2000 },
  { name: 'ANTISTREPTOLYSIN O (ASO TITRE), SERUM', code: 'SLASO', amount: 500 },
  { name: 'ANTITHYROID ANTIBODIES (MICROSOMAL & THYROGLOBULIN )', code: 'SLAN1', amount: 2500 },
  { name: 'ANTITHYROID ANTIBODY', code: 'ALATA', amount: 2500 },
  { name: 'Anti-TSH Receptor IgM,Serum by ECLIA', code: 'ALTSR', amount: 5000 },
  { name: 'Apolipoprotein A1,serum by Nephelometry', code: 'alap1', amount: 400 },
  { name: 'Apolipoprotein B,serum by Nephelometry', code: 'alap2', amount: 400 },
  { name: 'APOLIPROTEIN - A', code: 'SLAPO', amount: 1000 },
  { name: 'APOLIPROTEIN - B', code: 'SLAPB', amount: 800 },
  { name: 'ARTERIAL BLOOD GAS (ABG)', code: 'abgjj', amount: 2500 },
  { name: 'ASCITIC/ PERITONEAL FLUID ANALYSIS', code: 'SLASC', amount: 1500 },
  { name: 'ASPARTATE AMINOTRANSFERASE (AST/SGOT), SERUM', code: 'SLSGO', amount: 200 },
  { name: 'Aspergillus IgE', code: 'ighgg', amount: 2500 },
  { name: 'Aspergillus IgG', code: 'vcbcb', amount: 3000 },
  { name: 'BARBITURATE QUALITATIVE', code: 'SLBAL', amount: 1000 },
  { name: 'BARBITURATE QUANTITATIVE', code: 'SLBAQ', amount: 1000 },
  { name: 'Benzodizapine (Quantitative)', code: 'SLBEN', amount: 450 },
  { name: 'BETA 2 GLYCOPROTEIN IGM', code: 'SLBEM', amount: 1500 },
  { name: 'BETA 2 GLYCOPROTEIN IGG', code: 'SLB2G', amount: 1500 },
  { name: 'Beta -2-microglobulin', code: 'SLBE2', amount: 1800 },
  { name: 'Beta-2 microglobulin', code: 'SLB2M', amount: 1800 },
  { name: 'BETA-HUMAN CHORIONIC GONADOTROPIN ( B-HCG )', code: 'ALBET', amount: 800 },
  { name: 'BICARBONATE', code: 'SLBIC', amount: 600 },
  { name: 'Bile salt/Bile Pigment', code: 'SLUB1', amount: 100 },
  { name: 'BILIRUBIN (TOTAL, DIRECT, INDIRECT), SERUM', code: 'SLBIL', amount: 200 },
  { name: 'BIOPSY SMALL', code: 'BIOPS', amount: 1500 },
  { name: 'BLEEDING TIME & CLOTTING TIME', code: 'SLBTC', amount: 150 },
  { name: 'BLOOD CULTURE AND SENSITIVITY ( Aerobic)', code: 'ALBCR', amount: 1500 },
  { name: 'BLOOD CULTURE AND SENSITIVITY (Anaerobic)', code: 'bbbbb', amount: 1500 },
  { name: 'BLOOD UREA NITROGEN (24HRS URINE)', code: 'SLURR', amount: 400 },
  { name: 'BLOOD UREA NITROGEN WITH UREA', code: 'SLBUN', amount: 300 },
  { name: 'BNP (B type Natriuretic Peptide),Plasma by CMIA', code: 'SLBNP', amount: 3500 },
  { name: 'BONE MAROOW ASPIRATION + BIOPSY', code: 'SLAMB', amount: 4500 },
  { name: 'BONE MARROW REPORT', code: 'SLBON', amount: 10000 },
  { name: 'BONE TISSUE', code: 'BONEK', amount: 5000 },
  { name: 'BREAST IHC - ER, PR AND HER-2', code: 'SLERP', amount: 1000 },
  { name: 'BRUCELLA IGG AND IGM ANTIBODY', code: 'SLBGM', amount: 4000 },
  { name: 'BRUCELLA IgG AND IgM ANTIBODY', code: 'SLBR1', amount: 4000 },
  { name: 'Brucella-IgG antibodies,serum by EIA', code: 'SLBRG', amount: 2000 },
  { name: 'Brucella-IgM antibody,serum by EIA', code: 'SLBRM', amount: 2000 },
  { name: 'C - REACTIVE PROTEIN QUALITATIVE', code: 'SLCR1', amount: 500 },
  { name: 'C PEPTIDE', code: 'SLPEP', amount: 1000 },
  { name: 'C3 - COMPLEMENT 3,serum by Nephelometry', code: 'SLC31', amount: 1000 },
  { name: 'C3 AND C4 COMPLEMENT PANEL', code: 'SLC3L', amount: 1600 },
  { name: 'C4 COMPLEMENT LEVEL', code: 'slc41', amount: 1000 },
  { name: 'CA 15.3 (Cancer Antigen)', code: 'SLC15', amount: 2000 },
  { name: 'CA-125 (Cancer Antigen-125)', code: 'SLCA1', amount: 1260 },
  { name: 'CA19.9 ( Cancer Antigen 19.9 ), serum by CMIA', code: 'SLCA9', amount: 2000 },
  { name: 'CALCIUM, 24HRS URINE', code: 'CAL24', amount: 280 },
  { name: 'CALCIUM, SERUM', code: 'SLSCA', amount: 200 },
  { name: 'Calprotectin,stool', code: 'ALCAL', amount: 1500 },
  { name: 'CANCELLED TEST', code: 'SLCAN', amount: 1000 },
  { name: 'Carbamazepine (Tegretol), serum by CLIA', code: 'SLCAR', amount: 750 },
  { name: 'CAROTID DOPPLER STUDY', code: '12160', amount: 1000 },
  { name: 'CATECHOLAMINES BLOOD', code: 'SLCAT', amount: 1000 },
  { name: 'CD4/CD8 COUNT', code: 'SLCD4', amount: 2000 },
  { name: 'CD4/CD8 COUNT BY FLOW CYTOMETRY', code: 'ALCD4', amount: 1800 },
  { name: 'CEA TISSUE', code: 'SLCET', amount: 1500 },
  { name: 'CEA-CARCINO EMBRYONIC ANTIGEN,SERUM BY CMIA', code: 'SLCEA', amount: 1500 },
  { name: 'CELL BLOCK', code: 'CELLJ', amount: 2500 },
  { name: 'CEPHALOMETRY', code: '65432', amount: 1000 },
  { name: 'CEPHALOMETRY WITH CD', code: '77339', amount: 1000 },
  { name: 'Ceruloplasmin,serum by Nephelometry', code: 'SLCER', amount: 1000 },
  { name: 'CHICKEN POX ( VARICELL ) IgM', code: 'SLCCM', amount: 1200 },
  { name: 'CHICKEN POX ( VARICELLA ) IgG', code: 'SLCHK', amount: 1050 },
  { name: 'CHIKUNGUNYA IGM ANTIBODIES RAPID, SERUM', code: 'SLCHI', amount: 800 },
  { name: 'CHOLESTEROL, TOTAL', code: 'SLSCH', amount: 250 },
  { name: 'CHOLINESTERASE REPORT', code: 'SLCOE', amount: 1000 },
  { name: 'CMV (Cytomegalovirus) molecular (DNA) Detection (Qualitative)', code: 'slcmv', amount: 2000 },
  { name: 'CMV (Cytomegalovirus) Viral Load (DNA) Detection (Quantitative)', code: 'slcm3', amount: 2000 },
  { name: 'CMV DNA PCR - CSF', code: 'SLCDP', amount: 1000 },
  { name: 'CMV IgG-Avidity test', code: 'alcma', amount: 1200 },
  { name: 'COMPLETE BLOOD COUNT', code: '5part', amount: 300 },
  { name: 'COMPLETE BLOOD COUNT (3 PART)', code: '3part', amount: 200 },
  { name: 'COOMBS TEST, DIRECT, EDTA WHOLE BLOOD', code: 'SLDCT', amount: 700 },
  { name: 'CORONARY RISK PROFILE (LIPID PROFILE)', code: '1209A', amount: 700 },
  { name: 'COVID 19 ANTIGEN REPORT', code: 'covid', amount: 600 },
  { name: 'COVID 19/ SARS COV2 PCR', code: 'COVSA', amount: 1500 },
  { name: 'C-Peptide', code: 'alccp', amount: 1000 },
  { name: 'C-PEPTIDE - PP', code: 'cpppp', amount: 1000 },
  { name: 'CPK-MB', code: 'CPKMB', amount: 800 },
  { name: 'CPK-NAC', code: 'SLCPK', amount: 800 },
  { name: 'C-REACTIVE PROTEIN, SERUM (QUANTITATIVE)', code: 'CRPQN', amount: 500 },
  { name: 'CREATININE EGFR', code: 'algfr', amount: 1000 },
  { name: 'CREATININE, 24 HRS URINE', code: 'CRE24', amount: 1000 },
  { name: 'CREATININE, SERUM', code: 'SLSCT', amount: 200 },
  { name: 'Cryptococcus Antigen', code: 'alcry', amount: 1000 },
  { name: 'CRYPTOSPORIDIUM IN STOOL', code: 'SLCRS', amount: 1000 },
  { name: 'CSF REPORT', code: 'SLCSF', amount: 1500 },
  { name: 'CULTURE REPORT', code: 'ALBC1', amount: 1000 },
  { name: 'CULTURE REPORT', code: 'ALCS1', amount: 800 },
  { name: 'CULTURE REPORT', code: 'ALCUT', amount: 800 },
  { name: 'CYTOLOGY', code: 'SLCYT', amount: 1500 },
  { name: 'CYTOMEGALOVIRUS (CMV) DNA PCR', code: 'SLCMP', amount: 2000 },
  { name: 'CYTOMEGALOVIRUS (CMV ) IgG', code: 'SLCM1', amount: 600 },
  { name: 'CYTOMEGALOVIRUS (CMV ) IgM', code: 'SLCM2', amount: 600 },
  { name: 'D-Dimer QUANTITATIVE, CITRATE PLASMA', code: 'SLFD1', amount: 2000 },
  { name: 'Demo Y', code: 'A0123', amount: 1000 },
  { name: 'DemoTest3', code: '003', amount: 0 },
  { name: 'DemoTest5', code: 'DT', amount: 500 },
  { name: 'Dengue (NS1) Antigen', code: 'Dens1', amount: 600 },
  { name: 'DENGUE DUO RAPID SCREENING, SERUM', code: 'DENGU', amount: 1200 },
  { name: 'DIAGNOSTIC TAPPING', code: 'AMITK', amount: 1000 },
  { name: 'DIFFERENTIAL LEUCOCYTE COUNT', code: 'SLDLC', amount: 200 },
  { name: 'DIG. X-RAY(PORTABLE)', code: '15200', amount: 800 },
  { name: 'DIGOXIN', code: 'SLDIG', amount: 2000 },
  { name: 'DNA ( Double Strand ) Quantitative with titre by IF Titre.', code: 'sldni', amount: 1000 },
  { name: 'DOUBLE MARKER TEST', code: 'SLDOB', amount: 3000 },
  { name: 'Drugs of Abuse Panel', code: 'jkkjj', amount: 10000 },
  { name: 'EB VIRUS IgM', code: 'SLEBM', amount: 1000 },
  { name: 'EBV(VCA) - IgM antibody,serum', code: 'alebv', amount: 1800 },
  { name: 'ELASTOGRAPHY', code: 'ELAST', amount: 1000 },
  { name: 'ELASTOSCAN WITH BREAST & NECK', code: 'ESWBN', amount: 1000 },
  { name: 'ELECTROLYTES (Na /K /CL), SERUM', code: 'SLSEE', amount: 500 },
  { name: 'EMERGENCY ULTRASOUND', code: 'GRADE', amount: 1000 },
  { name: 'ER PR IHC TUMOUR MARKER', code: 'SLERR', amount: 1000 },
  { name: 'ERYTHROCYTE SEDIMENTATION RATE (ESR),EDTA BLOOD', code: 'SLES1', amount: 100 },
  { name: 'ERYTHROPOIETIN LEVEL', code: 'SLEPO', amount: 1000 },
  { name: 'ESTRADIOL (E2), SERUM', code: 'SLEST', amount: 710 },
  { name: 'ESTROGEN', code: 'SLESI', amount: 1000 },
  { name: 'F.N.A.C', code: 'SLFNC', amount: 2000 },
  { name: 'FACTOR VIII ACTIVITY', code: 'SLF8A', amount: 1000 },
  { name: 'FAVTOR V LEIDEN', code: 'SLFAV', amount: 1000 },
  { name: 'FERRITIN, SERUM', code: 'ALFER', amount: 800 },
  { name: 'FETAL BIO-PHYSICAL PROFILE', code: '12070', amount: 1000 },
  { name: 'FETAL DOPPLER STUDY', code: '13010', amount: 1000 },
  { name: 'Fibrinogen, Citrated Plasma', code: 'ALFI2', amount: 2000 },
  { name: 'FIBRINOGEN, CLOTTING ACTIVITY', code: 'SLFIB', amount: 2000 },
  { name: 'FIBROGEN', code: 'SLFIG', amount: 1500 },
  { name: 'FILARIA ANTIGEN', code: 'SLFIL', amount: 1000 },
  { name: 'FOLIC ACID, SERUM', code: 'SLFOL', amount: 1200 },
  { name: 'FOLLICLE STIMULATING HORMONE (FSH), SERUM', code: 'SLFSH', amount: 600 },
  { name: 'FOLLICULAR / OVULATION STUDY', code: '12060', amount: 1000 },
  { name: 'FREE PSA', code: 'SLFRP', amount: 1200 },
  { name: 'FREE TESTOSTERONE', code: 'SLFRT', amount: 1750 },
  { name: 'FREE THYROXINE - FT4', code: 'SLFT4', amount: 400 },
  { name: 'FREE TRIIODOTHYRONINE - FT3', code: 'SLFT3', amount: 800 },
  { name: 'FSH/LH RATIO', code: 'SLFSR', amount: 1800 },
  { name: 'FUNGAL CULTURE AND SENSITIVITY REPORT', code: 'SLFUN', amount: 1200 },
  { name: 'FUNGAL STAIN', code: 'SLFUS', amount: 1500 },
  { name: 'G-6-PD ACTIVITY, EDTA WHOLE BLOO', code: 'SLG6P', amount: 1000 },
  { name: 'GAMMA GLUTAMYL TRANSFERASE (GGT), SERUM', code: 'SLGGT', amount: 200 },
  { name: 'Genexpert MTB/RIF Resistance', code: 'ALGEN', amount: 3500 },
  { name: 'Gliadin antibodies', code: 'bfbfb', amount: 5000 },
  { name: 'GLUCOSE - POST PRANDIAL', code: 'SLBPP', amount: 60 },
  { name: 'GLUCOSE FASTING', code: 'SLBFF', amount: 60 },
  { name: 'GLUCOSE RANDOM, PLASMA', code: 'SLBSR', amount: 60 },
  { name: 'GLUCOSE TOLERANCE TEST (GTT)', code: 'SLGG1', amount: 300 },
  { name: 'GLYCOSYLATED HEMOGLOBIN ( HBA1C ), EDTA-WB', code: 'HBA1C', amount: 800 },
  { name: 'GRAM STAIN', code: 'SLGRA', amount: 1000 },
  { name: 'H1 N1', code: 'HHHHH', amount: 8500 },
  { name: 'HAV VIRAL LOAD', code: 'SLHVA', amount: 1000 },
  { name: 'HAV-IgG Ab to Hepatitis A VIrus,serum by CMIA', code: 'alha1', amount: 1150 },
  { name: 'HAV-IgM Ab to Hepatitis A Virus,serum by CMIA', code: 'alha2', amount: 1150 },
  { name: 'Hb ELECTROPHORESIS BY HPLC METHOD', code: 'ALHBE', amount: 1400 },
  { name: 'HBcAb - Total Ab to Hep-B Core Ag,Serum by CMIA', code: 'alhbc', amount: 850 },
  { name: 'HBcAb-IgM Ab Hepatitis B Core Antigen,serum - CMIA', code: 'alhb1', amount: 1500 },
  { name: 'HBcAb-Total Ab to Hep-B Core Ag,serum by CMIA', code: 'alhb2', amount: 1500 },
  { name: 'HBeAb - Ab to Hepatitis B envelop Ag,serum by CMIA', code: 'alhab', amount: 850 },
  { name: 'HBeAg - Hepatitis B Envelope ANtigen, Serum by CMIA', code: 'alhbg', amount: 850 },
  { name: 'HBeAg - Hepatitis B Envelope Antigen,serum by CMIA', code: 'alhee', amount: 850 },
  { name: 'HBsAg,serum by CMIA', code: 'alhbs', amount: 600 },
  { name: 'HBsAg,serum by CMIA.', code: 'ALHE1', amount: 600 },
  { name: 'HBV DNA PCR', code: 'ALHBV', amount: 6000 },
  { name: 'HBV Qualitative Real Time PCR Report', code: 'SLHVB', amount: 6000 },
  { name: 'HBV Quantitative PCR', code: 'SLPC3', amount: 6000 },
  { name: 'HDL CHOLESTEROL, SERUM', code: 'SLHDL', amount: 300 },
  { name: 'Helicobacter Pylori - IgA antibodies,serum by EIA', code: 'SLHYA', amount: 1100 },
  { name: 'Helicobacter Pylori - IgG antibodies,serum by EIA', code: 'SLHPG', amount: 1100 },
  { name: 'HEMOGLOBIN & HEMATOCRIT, EDTA WHOLE BLOOD', code: 'SLHEM', amount: 200 },
  { name: 'HEP B CORE ANTIGEN', code: 'SLHCO', amount: 1000 },
  { name: 'HEPATITIS B VIRAL LOAD', code: 'SLBVI', amount: 6000 },
  { name: 'HEPATITIS " A " VIRUS (HAV) IgM ANTIBODIES', code: 'SUHAV', amount: 900 },
  { name: 'HEPATITIS "A" VIRUS (HAV) IgG ANTIBODIES', code: 'SUHGG', amount: 900 },
  { name: 'HEPATITIS A IGM, SERUM', code: 'ARHAV', amount: 1000 },
  { name: 'HEPATITIS B CORE ANTIBODY:TOTAL (ANTI -HBC IgG&IgM)', code: 'SLHEB', amount: 1000 },
  { name: 'HEPATITIS B e ANTIGEN.', code: 'SLHE1', amount: 1000 },
  { name: 'HEPATITIS B SURFACE ANTIBODIES(HBsAb)', code: 'SLHBS', amount: 1000 },
  { name: 'HEPATITIS B SURFACE ANTIGEN (HBsAG), SERUM', code: 'SLHBV', amount: 300 },
  { name: 'HEPATITIS B TOTAL PROFILE (AuAg,HBS antigen,HBEAG, HBCAG,HBEAG)', code: 'SLHBP', amount: 1000 },
  { name: 'HEPATITIS B VIRAL LOAD', code: 'SLHBD', amount: 6000 },
  { name: 'HEPATITIS C ANTIBODY', code: 'SLHC1', amount: 600 },
  { name: 'HEPATITIS C VIRUS ABS (HCV), SERUM', code: 'SLHCV', amount: 600 },
  { name: 'HEPATITIS E VIRUS IgM ANTIBODY', code: 'ALHEV', amount: 1000 },
  { name: 'HEPATITIS PROFILE (HAV IGM,HEV IGM,HCV,HEPATITIS B PROFILE)', code: 'SLHBB', amount: 1000 },
  { name: 'HERPES SIMPLEX VIRUS (HSV 1 & 2) MOLECULAR DETECTION', code: 'SLPC4', amount: 1000 },
  { name: 'HERPES SIMPLEX VIRUS IgG ( HSV I AND II )', code: 'SLHS1', amount: 600 },
  { name: 'HERPES SIMPLEX VIRUS IgM ( HSV I AND II )', code: 'SLHS2', amount: 600 },
  { name: 'HEV-IgG Ab to Hepatitis E Virus by EIA', code: 'alhe3', amount: 1150 },
  { name: 'HEV-IgM Ab to Hepatitis E Virus,serum by EIA', code: 'alhe4', amount: 1150 },
  { name: 'HGH -HUMAN GROWTH HORMONE,SERUM BY CLIA', code: 'SLGRO', amount: 800 },
  { name: 'HIGH SENSITIVE C REACTIVE PROTEIN (HsCRP), SERUM', code: 'CRPQU', amount: 800 },
  { name: 'HISTOPATHOLOGY [ BIG SPECIMEN ]', code: 'HISTO', amount: 7000 },
  { name: 'HISTOPATHOLOGY BREAST BIOPSY', code: 'HISTM', amount: 2500 },
  { name: 'HISTOPATHOLOGY EXTRA LARGE', code: 'HISTE', amount: 7000 },
  { name: 'HISTOPATHOLOGY LARGE', code: 'HISTJ', amount: 7000 },
  { name: 'HISTOPATHOLOGY MEDIUM', code: 'MEDIU', amount: 2500 },
  { name: 'HISTOPATHOLOGY OF CYST', code: 'CYSTT', amount: 2500 },
  { name: 'HISTOPATHOLOGY OF THYROID GLAND', code: 'GLAND', amount: 4500 },
  { name: 'HISTOPATHOLOGY SMALL', code: 'SLHEP', amount: 1500 },
  { name: 'HIV 1 VIRAL LOAD BY COBAS TAQMAN', code: 'SLVIR', amount: 1000 },
  { name: 'HIV ANTIBODIES, SERUM', code: 'SLHIV', amount: 400 },
  { name: 'HIV MOLECULAR DETECTION', code: 'SLPC1', amount: 1000 },
  { name: 'HIV PCR DNA', code: 'SLHID', amount: 1000 },
  { name: 'HIV proviral DNA detection PCR', code: 'SLHPC', amount: 1000 },
  { name: 'HIV VIRAL LOAD', code: 'SLH13', amount: 1000 },
  { name: 'HLA - B27 By PCR', code: 'SLHLP', amount: 6000 },
  { name: 'HLA-B27 associated Ankylosing spondylitis Detection Test', code: 'alhla', amount: 3800 },
  { name: 'HLA-B27 Detection, EDTA Whole Blood', code: 'SLH27', amount: 2500 },
  { name: 'HOMOCYSTEINE', code: 'SLHOM', amount: 1300 },
  { name: 'HPE', code: 'hpemm', amount: 3000 },
  { name: 'HPE ( large )', code: 'hpela', amount: 7000 },
  { name: 'HPE APPENDIX SAMPLE', code: 'APPEN', amount: 5000 },
  { name: 'HPE BLOCK & SLIDE', code: 'HPEBB', amount: 7000 },
  { name: 'HPE BLOCK FOR OPINION', code: 'OPINI', amount: 1400 },
  { name: 'HPE BLOCKS FOR OPINION', code: 'BLOCK', amount: 1700 },
  { name: 'HPE BREAST SAMPLE', code: 'HPEBR', amount: 3000 },
  { name: 'HPE COLON', code: 'COLON', amount: 3000 },
  { name: 'HPE GALL BLADDER', code: 'BLADD', amount: 3500 },
  { name: 'HPE ORAL BIOPSY', code: 'ORALB', amount: 2000 },
  { name: 'HPE RADICAL NECK MANDIBLE', code: 'HPERR', amount: 3000 },
  { name: 'HPE SEBASCEOUS CYST', code: 'HPEss', amount: 2100 },
  { name: 'HPE TISSUE SAMPLE', code: 'HPETS', amount: 6000 },
  { name: 'HSV I & II IgG And IgM', code: 'alhsv', amount: 2400 },
  { name: 'HSV-1 IgG Ab to Herpes Simplex Virus 1,by EIA', code: 'alhs1', amount: 1500 },
  { name: 'HSV-1 IgM Ab to Herpes Simplex Virus 1,by EIA', code: 'alhs2', amount: 1500 },
  { name: 'HSV-2 IgG Ab to Herpes Simplex Virus 2,by EIA', code: 'alhs3', amount: 1500 },
  { name: 'HSV-2 IgM Ab to Herpes Simplex Virus 2,by EIA', code: 'alhs4', amount: 1500 },
  { name: 'IgA', code: 'iiiii', amount: 1500 },
  { name: 'IGF - 1 (SOMATOMEDIN C)', code: 'SLIGF', amount: 1000 },
  { name: 'IgG LEVEL, serum by Nephelometry', code: 'SLIGG', amount: 700 },
  { name: 'IHC', code: 'SLIHC', amount: 8000 },
  { name: 'IMMUNOGLOBULIN PROFILE', code: 'SLIMQ', amount: 1000 },
  { name: 'IMMUNOHISTOCHEMICAL ASSAY - HER 2', code: 'SLHER', amount: 8000 },
  { name: 'INDIA INK PREPARATION', code: 'SLIND', amount: 2000 },
  { name: 'INDIRECT COOMBS TEST', code: 'SLICT', amount: 700 },
  { name: 'INHIBIN B', code: 'ghggg', amount: 3500 },
  { name: 'INSULIN', code: 'SLINS', amount: 2000 },
  { name: 'INSULIN (PP) REPORT', code: 'SLINP', amount: 1000 },
  { name: 'INSULIN ANTIBODY', code: 'SLISA', amount: 2000 },
  { name: 'INSULINE ANTIBODY', code: 'SLINA', amount: 1000 },
  { name: 'INTERLUKIN - 6 (IL-6)', code: 'IL6', amount: 4500 },
  { name: 'INTUSSUSCEPTION REDUCTION', code: 'INTS1', amount: 1000 },
  { name: 'IONIC CALCIUM', code: 'SLION', amount: 500 },
  { name: 'IRON, SERUM', code: 'FEIRO', amount: 500 },
  { name: 'IRON STUDIES (IRON,TIBC,UIBC,% SAT)', code: 'IRONS', amount: 1000 },
  { name: 'KARYOPTYPING BLOOD', code: 'SLKAR', amount: 5000 },
  { name: 'Karyotyping', code: 'SLKAY', amount: 5000 },
  { name: 'KIDNEY FUNCTION TEST', code: 'kft', amount: 800 },
  { name: 'KIDNEY PANEL 1', code: 'KFT11', amount: 800 },
  { name: 'KOH MOUNT', code: 'SLKOH', amount: 1000 },
  { name: 'L S SPINE LAT (EXTENSION/FLEXION)', code: '80001', amount: 1000 },
  { name: 'LACTATE DEHYDROGENASE ( LDH )', code: 'SLLDH', amount: 800 },
  { name: 'LDH, BODY FLUID', code: '01211', amount: 800 },
  { name: 'LDL CHOLESTROL , SERUM', code: 'SLLDL', amount: 450 },
  { name: 'Lead,Blood by Electrochemical (ASV)', code: 'SLLED', amount: 5000 },
  { name: 'LEcell Phenomenon', code: 'SLLEC', amount: 500 },
  { name: 'LEPTOSPIRA IGG ANTIBODY RAPID', code: 'SLLE2', amount: 1500 },
  { name: 'LEPTOSPIRA IGM ANTIBODY RAPID', code: 'SLLEP', amount: 1500 },
  { name: 'LFT NEW', code: 'LFTNW', amount: 800 },
  { name: 'LIPASE, SERUM', code: 'SLLIF', amount: 700 },
  { name: 'LIPID PROFILE, SERUM', code: 'SLLPR', amount: 700 },
  { name: 'LIPOPROTEIN -( A )', code: 'SLLPA', amount: 2000 },
  { name: 'Lithium, serum by ISE', code: 'SLLIT', amount: 1500 },
  { name: 'LIVER BIOPSY BANFF SCORE TEST', code: 'LIVER', amount: 4000 },
  { name: 'LIVER CHECK PANEL', code: 'LCHCK', amount: 800 },
  { name: 'LIVER FUNCTION TEST W/O GGT', code: 'SLLFT', amount: 800 },
  { name: 'LKM1-Liver Kidney Microsome abs,serum by IF', code: 'SLLKM', amount: 2500 },
  { name: 'LUPUS ANTICOAGULANT', code: 'SLLAP', amount: 1000 },
  { name: 'LUTEINIZING HORMONE (LH), SERUM', code: 'SLLHH', amount: 600 },
  { name: 'MAGNESIUM, SERUM', code: 'SLMAG', amount: 300 },
  { name: 'MALARIA ANTIGEN DETECTION, WHOLE BLOOD', code: 'SLOPT', amount: 400 },
  { name: 'MALARIAL PARASITE (M.P), EDTA WHOLE BLOOD/SMEA', code: 'SLMPA', amount: 150 },
  { name: 'MAMMOGRAPHY', code: '12220', amount: 1000 },
  { name: 'MATERNAL SERUM SCREEN 4 QUADRUPLE TEST', code: 'SLQUA', amount: 3500 },
  { name: 'Measles ( Rubeola ) - IgG ANtibodies, serum by EIA', code: 'slmeg', amount: 1200 },
  { name: 'MICROALBUMIN WITH ACR, URINE', code: 'ALACR', amount: 1000 },
  { name: 'MICROPROTEIN', code: 'SLMIR', amount: 200 },
  { name: 'Mumps-IgG Antibodies,serum by EIA', code: 'SLMIA', amount: 1250 },
  { name: 'Mumps-IgM antibodies,serum', code: 'SLMIM', amount: 1600 },
  { name: 'MUSCULOSKELETAL USG', code: '17600', amount: 1000 },
  { name: 'MYCOBACTERIUM SPP. MOLECULAR DETECTION', code: 'ALDNA', amount: 1000 },
  { name: 'Mycobacterium Tuberculosis QUALITATIVE REAL TIME PCR REPORT', code: 'SLTBR', amount: 1000 },
  { name: 'Mycoplasma pneumoniae Antibody IgG', code: 'SLMIG', amount: 2200 },
  { name: 'Mycoplasma pneumoniae Antibody IGM', code: 'SLMYO', amount: 1000 },
  { name: 'newdemo', code: 'ne', amount: 500 },
  { name: 'NS1 ANTIGEN (TITRE) REPORT', code: 'ALDE3', amount: 1000 },
  { name: 'N-TERMINAL PRO B-TYPE NATRIURETIC PEPTIDE (NT PRO BNP), SERUM', code: 'SLBN1', amount: 3500 },
  { name: 'OCCLUSAL MANDIBLE', code: '16540', amount: 1000 },
  { name: 'OCCLUSAL MANDIBLE & MAXILLA', code: '10297', amount: 1000 },
  { name: 'OCCLUSAL MAXILLA', code: '66220', amount: 1000 },
  { name: 'OPG WITH CD', code: '18280', amount: 1000 },
  { name: 'OPG WITH CEPHALOMETRY', code: '16260', amount: 1000 },
  { name: 'OPG WITH CEPHALOMETRY AND CD', code: 'OPGWC', amount: 1000 },
  { name: 'OPG X-RAY', code: '15970', amount: 1000 },
  { name: 'OPG X-RAY(ONLY CD)', code: '16240', amount: 1000 },
  { name: 'ORBIT AP', code: 'ORBIT', amount: 1000 },
  { name: 'ORBIT AP/LAT', code: '17460', amount: 1000 },
  { name: 'OSMOTIC FRAGILITY TEST', code: 'SLOSM', amount: 1000 },
  { name: 'P.C.R. for M.Tuberculosis Complex.', code: 'altbp', amount: 5000 },
  { name: 'P24 Antigen', code: 'SLP24', amount: 5000 },
  { name: 'PAP SMEAR REPORT', code: 'SLPAP', amount: 1500 },
  { name: 'PAPP-A (PREGNANCY ASSOCIATED PLASMA PROTEIN-A)', code: 'SLPPP', amount: 2500 },
  { name: 'PARATHYROID HORMONE LEVEL', code: 'SLPTH', amount: 2500 },
  { name: 'PAS STAIN', code: 'PASmm', amount: 1500 },
  { name: 'PCR For TB', code: 'ALPCR', amount: 5000 },
  { name: 'PD-L1', code: 'PDLAA', amount: 2500 },
  { name: 'PENILE DOPPLER', code: 'PNILE', amount: 1000 },
  { name: 'PERIPHERAL SMEAR EXAMINATION, EDTA-WB', code: 'SLPBS', amount: 150 },
  { name: 'PERIPHERAL VASCULAR STUDY (BOTH LIMB)', code: '17660', amount: 1000 },
  { name: 'PERIPHERAL VASCULAR STUDY (SINGLE LIMB)', code: '12140', amount: 1000 },
  { name: 'PHENOBARBITONE LEVEL', code: 'SLBAR', amount: 5000 },
  { name: 'Phenytoin (Eptoin), serum by CLIA', code: 'SLPHY', amount: 3000 },
  { name: 'PHOSPHORUS, SERUM', code: 'SLSPS', amount: 300 },
  { name: 'PIGTAIL ABSCESS DRAINAGE', code: 'PIGTA', amount: 1000 },
  { name: 'PLATELET COUNT, EDTA WHOLE BLOOD', code: 'SLPTC', amount: 200 },
  { name: 'PLEURAL FLUID REPORT', code: 'SLPLU', amount: 1500 },
  { name: 'PORTABLE EXTRA CHARGE', code: 'PORTX', amount: 1000 },
  { name: 'POTASSIUM, SERUM', code: 'SLPOT', amount: 220 },
  { name: 'POTASSIUM, URINE SPOT', code: 'SLUSS', amount: 300 },
  { name: 'PREGNANCY TEST, SPOT URINE (UPT)', code: 'SLUPT', amount: 200 },
  { name: 'PROCALCITONIN', code: 'ALPRQ', amount: 3500 },
  { name: 'PROGESTERONE, SERUM', code: 'SLPRG', amount: 650 },
  { name: 'PROLACTIN, SERUM', code: 'SLPRO', amount: 600 },
  { name: 'PROSTATE SPECIFIC ANTIGEN (PSA), SERUM', code: 'SLPSA', amount: 1000 },
  { name: 'PROTEIN C, FUNCTIONAL', code: 'SLPRC', amount: 5000 },
  { name: 'PROTEIN S, FUNCTIONAL', code: 'SLPRS', amount: 5000 },
  { name: 'PROTEIN, 24HRS URINE', code: 'PRO24', amount: 1000 },
  { name: 'PROTEIN, SERUM', code: 'PROTS', amount: 300 },
  { name: 'PROTHROMBIN TIME, CITRATE PLASMA', code: 'SLPTA', amount: 500 },
  { name: 'PULMONARY FUNCTION TEST', code: '12600', amount: 1000 },
  { name: 'PUS CULTURE AND SENSITIVITY', code: 'ALPCT', amount: 1500 },
  { name: 'Quadruple Marker', code: 'quadr', amount: 3500 },
  { name: 'QUANTIFERON-TB GOLD;GAMMA INTERFERON', code: 'SLTGG', amount: 3500 },
  { name: 'QUANTITATIVE RHEUMATOID FACTOR , SERUM', code: 'RAFQU', amount: 500 },
  { name: 'RAPID TYPHI IGM, SERUM/PLASMA EDTA/EDTA WB', code: 'wgm', amount: 500 },
  { name: 'RBC Indices', code: 'SLRBC', amount: 200 },
  { name: 'REDUCING SUBSUTANCEC', code: 'SLRED', amount: 200 },
  { name: 'RENAL BIOPSY BY IMMUNOFLORESCENCE', code: 'RENAL', amount: 3500 },
  { name: 'RENAL DOPPLER STUDY', code: '12150', amount: 1000 },
  { name: 'RENAL FUNCTION TEST', code: 'SLRFT', amount: 800 },
  { name: 'REPORT (HBA1C)', code: 'SLGH1', amount: 600 },
  { name: 'RETICULOCYTE COUNT, EDTA WHOLE BLOOD', code: 'SLRTC', amount: 1000 },
  { name: 'Rh (Ant D) Antibody titre,serum', code: 'alrha', amount: 800 },
  { name: 'RHEUMATOID FACTOR (RA FACTOR), SERUM', code: 'SLRAF', amount: 500 },
  { name: 'RICKETSIAL ANTIBODY TEST', code: 'SLRI1', amount: 1000 },
  { name: 'RUBELLA IgG', code: 'alru1', amount: 600 },
  { name: 'RUBELLA IgM', code: 'ALRU3', amount: 600 },
  { name: 'Rubella-IgG antibodies,by CMIA', code: 'ALRUG', amount: 1000 },
  { name: 'Rubella-IgM antibodies,by CMIA', code: 'ALRUM', amount: 1000 },
  { name: 'RUT', code: '29040', amount: 1000 },
  { name: 'S. ACID PHOSPHATASE', code: 'SLACA', amount: 400 },
  { name: 'SALMONELLA TYPHI IgM', code: 'SLSTY', amount: 550 },
  { name: 'Salmonella typhi IgG', code: 'SLSAT', amount: 600 },
  { name: 'SCRUB TYPHUS RAPID ANTIBODIES (IGG / IGM)', code: 'TYPHS', amount: 2500 },
  { name: 'SEGMENTAL CBCT', code: 'CBCTS', amount: 1000 },
  { name: 'SEMEN ANALYSIS', code: 'SLSEM', amount: 500 },
  { name: 'SEMEN CULTURE AND SENSITIVITY', code: 'ALSEM', amount: 1500 },
  { name: 'SEMEN EXAMINATION', code: 'SLSIM', amount: 1000 },
  { name: 'SEMEN WASH', code: 'SLWAS', amount: 1000 },
  { name: 'SERUM BICARBONATE', code: 'SLBI1', amount: 250 },
  { name: 'Serum IgG', code: 'igggg', amount: 1500 },
  { name: 'SERUM MYOGLOBIN', code: 'SLMYS', amount: 1000 },
  { name: 'Serum Osmolarity', code: 'SLOSB', amount: 1000 },
  { name: 'SERUM PROTEIN ELECTROPHORESIS REPORT', code: 'SLPR1', amount: 1500 },
  { name: 'SICKLING TEST, EDTA WHOLE BLOOD', code: 'SLSIC', amount: 1000 },
  { name: 'SKIN TEST MANTOUX', code: 'VGCAS', amount: 200 },
  { name: 'SMOOTH MUSCLE ANTIBODY', code: 'SLSAB', amount: 1000 },
  { name: 'SODIUM, SERUM', code: 'SLSOM', amount: 220 },
  { name: 'SODIUM, URINE', code: 'SLUOD', amount: 300 },
  { name: 'SODIUM, URINE SPOT', code: 'SLUBB', amount: 200 },
  { name: 'SONO ELASTO SCAN', code: '87421', amount: 1000 },
  { name: 'SPUTUM CULTURE AND SENSITIVITY', code: 'ALSCS', amount: 1500 },
  { name: 'SPUTUM ROUTINE', code: 'sp111', amount: 1000 },
  { name: 'Sr CORTISOL', code: 'SLCOR', amount: 1000 },
  { name: 'SR CREATININE & SR ALBUMIN RATIO', code: 'SLCRR', amount: 1000 },
  { name: 'SR INSULINE', code: 'ALINF', amount: 600 },
  { name: 'Sr. B2 microglobulin', code: 'SLBMI', amount: 1800 },
  { name: 'SR. COPPER', code: 'SLCOP', amount: 750 },
  { name: 'Stone Analysis', code: 'SLSTA', amount: 1100 },
  { name: 'Stone Analysis Kidney (Renal) Calculus', code: 'alsta', amount: 1100 },
  { name: 'STOOL CULTURE AND SENSITIVITY', code: 'ALSTO', amount: 1500 },
  { name: 'STOOL EXAMINATION', code: 'SLSTO', amount: 500 },
  { name: 'STOOL FOR HANGING DROP', code: 'SLSHD', amount: 500 },
  { name: 'STOOL FOR MODIFIED ZN STAIN', code: 'SLMOD', amount: 1000 },
  { name: 'STOOL FOR OCCULT BLOOD', code: 'SLOBT', amount: 250 },
  { name: 'SUDAN III', code: 'sudan', amount: 1000 },
  { name: 'SWAB CULTURE REPORT', code: 'SLOTS', amount: 1500 },
  { name: 'SWAB CULTURE AND SENSITIVITY', code: 'SLSWA', amount: 1500 },
  { name: 'SYNOVIAL FLUID EXAMINATION', code: 'SYNIL', amount: 1500 },
  { name: 'TB RNA PCR', code: 'ALRNA', amount: 2000 },
  { name: 'TB( Mycobacterium spp.)DNA detection', code: 'SLTBD', amount: 1000 },
  { name: 'test', code: 'testf', amount: 10 },
  { name: 'TESTOSTERONE TOTAL', code: 'SLTES', amount: 800 },
  { name: 'THERAPEUTIC USG GUIDED PLEURAL TAPPING', code: '12680', amount: 1000 },
  { name: 'THROAT SWAB CULTURE AND SENSITIVITY', code: 'ALTSC', amount: 1500 },
  { name: 'Thyroglobulin level, serum by CLIA', code: 'SLTHY', amount: 1550 },
  { name: 'THYROID PANEL II (FT3,FT4,TSH) SERUM', code: 'SLFTF', amount: 800 },
  { name: 'THYROID PANEL, SERUM', code: 'SLTFT', amount: 600 },
  { name: 'THYROID STIMULATING HORMONE-TSH(ULTRA)', code: 'SLTSH', amount: 350 },
  { name: 'TISSUE TRANSGLUTAMINASE ANTIBODY IgA', code: 'SLTTG', amount: 1000 },
  { name: 'TORCH - 10 IGM / IGG', code: 'alt10', amount: 4000 },
  { name: 'TORCH IgG & IgM', code: 'SLTOR', amount: 3200 },
  { name: 'TORCH IgG', code: 'SLTOG', amount: 1300 },
  { name: 'TORCH IgG / IgM', code: 'ALTOR', amount: 2500 },
  { name: 'TORCH IgM', code: 'SLTRM', amount: 1300 },
  { name: 'TOTAL IgE', code: 'SLIGE', amount: 1500 },
  { name: 'TOTAL PROTEIN with ALBUMIN,GLOBULIN, A/G RATIO', code: 'SLSPR', amount: 300 },
  { name: 'TOTAL THYROXINE T4, SERUM', code: 'SLT41', amount: 200 },
  { name: 'TOTAL TRIIODOTHYRONINE T3, SERUM', code: 'SLT31', amount: 200 },
  { name: 'TOTAL WBC COUNT', code: 'SLTLC', amount: 200 },
  { name: 'TOXOPLASMA IgG', code: 'SLTO1', amount: 600 },
  { name: 'TOXOPLASMA IgM', code: 'SLTO2', amount: 600 },
  { name: 'Toxoplasma-IgG antibodies,by CMIA', code: 'ALTOG', amount: 1000 },
  { name: 'Toxoplasma-IgM antibodies,by CMIA', code: 'ALTOM', amount: 1000 },
  { name: 'TPHA-Treponemaa Pallidium Haemagglutination', code: 'SLTPH', amount: 1000 },
  { name: 'Transferrin saturation', code: 'SLTFS', amount: 400 },
  { name: 'TRANSFERRIN SATURATION', code: 'SLTRN', amount: 1000 },
  { name: 'TRANS-VAGINAL USG', code: '12120', amount: 1000 },
  { name: 'TRIGLYCERIDES, SERUM', code: 'SLTRI', amount: 250 },
  { name: 'TRIPLE MARKER', code: 'SLTR2', amount: 3200 },
  { name: 'TROPONIN I QUANTITATIVE', code: 'SLTR1', amount: 1500 },
  { name: 'Troponin T', code: 'SLTRP', amount: 1500 },
  { name: 'TRUS', code: 'TRUS1', amount: 1000 },
  { name: 'TSH RECEPTOR ANTIBODY', code: 'SLRTA', amount: 3200 },
  { name: 'TTG-Tissue transglutasminase-IgA', code: 'SLTT1', amount: 3500 },
  { name: 'TUBERCULIN TEST', code: 'SLTTT', amount: 200 },
  { name: 'TUMOR MARKAR', code: 'SLTUM', amount: 1000 },
  { name: 'URIC ACID, SERUM', code: 'SLSUR', amount: 200 },
  { name: 'URINALYSIS (URINE ROUTINE & MICROSCOPY)', code: 'URINE', amount: 100 },
  { name: 'Urinary Creatinine Clearence in 24 hours', code: 'alcru', amount: 300 },
  { name: 'URINARY ELECTROLYTES (NA/K/CL)', code: 'SLSEU', amount: 500 },
  { name: 'URINARY PROTEIN CREATININE RATIO (SPOT URINE)', code: 'SLUPC', amount: 1000 },
  { name: 'URINARY SPOT CHLORIDE', code: 'SLUSH', amount: 500 },
  { name: 'URINARY SPOT CREATININE', code: 'SLUSC', amount: 500 },
  { name: 'URINE FOR LEPTOSPIRA', code: 'SLULP', amount: 1000 },
  { name: 'URINE - KETONES', code: 'SLUKT', amount: 100 },
  { name: 'URINE AFB', code: 'SLUAF', amount: 1500 },
  { name: 'URINE ALBUMIN', code: 'ALALB', amount: 100 },
  { name: 'URINE ALBUMIN/SUGAR', code: 'SLUAB', amount: 100 },
  { name: 'URINE CHLORIDE', code: 'SLUCH', amount: 200 },
  { name: 'URINE COTININE', code: 'ALCOT', amount: 2000 },
  { name: 'URINE CREATININE LEVEL', code: 'SLUCL', amount: 300 },
  { name: 'URINE CULTURE AND SENSITIVITY', code: 'ALUCT', amount: 1260 },
  { name: 'Urine for Bence Jones Protein', code: 'SLUBP', amount: 1000 },
  { name: 'URINE FOR BILE SALT & BILE PIGMENT', code: 'SLBSP', amount: 100 },
  { name: 'URINE FOR MELIGNANT CELL', code: 'SLUMC', amount: 1000 },
  { name: 'URINE FOR SUGAR & ACETONE', code: 'SLUSA', amount: 1000 },
  { name: 'URINE HOMOCYSTEINE', code: 'SLUHO', amount: 1000 },
  { name: 'URINE METANEPHRINE', code: 'SLMET', amount: 1000 },
  { name: 'URINE MICRO ALBUMIN', code: 'SLURL', amount: 1000 },
  { name: 'URINE MICROALBUMIN', code: 'SLUMR', amount: 600 },
  { name: 'URINE NICOTINE LEVEL', code: 'SLNI1', amount: 1000 },
  { name: 'URINE NICOTININE', code: 'SLUNI', amount: 1000 },
  { name: 'URINE OCCULT BLOOD', code: 'SLUOB', amount: 1000 },
  { name: 'Urine Osmolarity', code: 'SLOSU', amount: 1000 },
  { name: 'Urine Protein Electrophoresis', code: 'SLUEP', amount: 1500 },
  { name: 'URINE SPOT PHOSPHORUS', code: 'SLUST', amount: 200 },
  { name: 'URINE SUGAR ( RANDOM )', code: 'ALUSR', amount: 50 },
  { name: 'URINE SUGAR (FASTING)', code: 'SLUSF', amount: 50 },
  { name: 'URINE SUGAR (PP)', code: 'SLUSP', amount: 50 },
  { name: 'USG ABDOMEN', code: '12030', amount: 1000 },
  { name: 'USG BREAST', code: '17630', amount: 1000 },
  { name: 'USG CRANIUM (INFANTS)', code: '12130', amount: 1000 },
  { name: 'USG DOPPLER STUDY(BOTH LIMBS)', code: '12345', amount: 1000 },
  { name: 'USG DOPPLER STUDY(SINGLE LIMB)', code: 'DOPPL', amount: 1000 },
  { name: 'USG GUIDED ABSCESS DRAINAGE', code: '12080', amount: 1000 },
  { name: 'USG GUIDED ASCITIC TAPPING', code: '17650', amount: 1000 },
  { name: 'USG GUIDED PERICARDIAL TAPPING', code: '65701', amount: 1000 },
  { name: 'USG NECK', code: '17620', amount: 1000 },
  { name: 'USG OBSTETRICS', code: '12040', amount: 1000 },
  { name: 'USG PACKAGE (OBSTETRICS)', code: '12050', amount: 1000 },
  { name: 'USG PORTABLE', code: '16560', amount: 1000 },
  { name: 'USG SCREENING', code: '12100', amount: 1000 },
  { name: 'USG SCROTUM', code: '17610', amount: 1000 },
  { name: 'USG SMALL PARTS (thyroid,neck,scrotum e.t.c)', code: '12110', amount: 1000 },
  { name: 'USG THYROID', code: '17640', amount: 1000 },
  { name: 'UTERUS CERVIX OVARY FT', code: 'UTERU', amount: 5000 },
  { name: 'UTERUS WITH FIBROID', code: 'SLUTF', amount: 5000 },
  { name: 'Valproic Acid', code: 'SLVAL', amount: 1800 },
  { name: 'Valproic Acid, serum by CLIA', code: 'SLVA1', amount: 1800 },
  { name: 'Varicella Zoster-IgG antibodies, by EIA', code: 'SLMRA', amount: 1000 },
  { name: 'Varicella Zoster-IgM antibodies, by EIA', code: 'SLMRM', amount: 1000 },
  { name: 'VDRL (MODIFIED),SERUM', code: 'SLVDR', amount: 300 },
  { name: 'VENOUS BLOOD GAS(VBG)', code: 'VBGVB', amount: 1200 },
  { name: 'VERICELLA ZOSTER -IgG ANTIBODIES', code: 'SLVE1', amount: 1050 },
  { name: 'VITAMIN A', code: 'SLVIA', amount: 4200 },
  { name: 'VITAMIN B12 (CYANOCOBALAMINE), SERUM', code: 'SLB12', amount: 1000 },
  { name: 'VITAMIN C', code: 'SLVIC', amount: 1000 },
  { name: 'WEIL FELIX TEST', code: 'SLWFT', amount: 1000 },
  { name: 'WESTERN BLOT REPORT', code: 'SLWES', amount: 2500 },
  { name: 'WIDAL TEST, SERUM', code: 'SLWID', amount: 200 },
  { name: 'X-RAY ABDOMEN ERECT & SUPINE', code: '17200', amount: 1000 },
  { name: 'X-RAY ABDOMEN ERECT AP', code: '17190', amount: 1000 },
  { name: 'X-RAY ABDOMEN SUPINE', code: '23eww', amount: 1000 },
  { name: 'X-RAY ARM WITH ELBOW AP/LAT', code: '17070', amount: 1000 },
  { name: 'X-RAY B/L ANKLE AP/LAT', code: '11225', amount: 1000 },
  { name: 'X-RAY B/L CLAVICLE AP', code: '66443', amount: 1000 },
  { name: 'X-RAY B/L HIPJOINT AP/LAT', code: '16950', amount: 1000 },
  { name: 'X-RAY B/L KNEE AP/LAT', code: '88440', amount: 1000 },
  { name: 'X-RAY B/L KNEE STANDING AP', code: '87878', amount: 1000 },
  { name: 'X-RAY B/L MASTOIDS LAT-OBLIQUE VIEW', code: '17970', amount: 1000 },
  { name: 'X-RAY B/L SI JOINT AP', code: '17500', amount: 1000 },
  { name: 'X-RAY B/L SI JOINT OBLIQUE', code: '55001', amount: 1000 },
  { name: 'X-RAY B/L TM JOINT AP VIEW', code: '11116', amount: 1000 },
  { name: 'X-RAY B/L TM JOINT LAT-OBLIQUE', code: '11118', amount: 1000 },
  { name: 'X-RAY CERVICO-THORACIC SPINE SWIMMERS VIEW', code: '77008', amount: 1000 },
  { name: 'X-RAY CHEST AP VIEW', code: '17160', amount: 1000 },
  { name: 'X-RAY CHEST APICOGRAM', code: '18796', amount: 1000 },
  { name: 'X-RAY CHEST LAT VIEW', code: '55554', amount: 1000 },
  { name: 'X-RAY CHEST LT OBLIQUE VIEW', code: '11005', amount: 1000 },
  { name: 'X-RAY CHEST PA VIEW', code: '17150', amount: 1000 },
  { name: 'X-RAY CHEST PA VIEW (PACKAGE)', code: 'XRCPP', amount: 1000 },
  { name: 'X-RAY CHEST RT OBLIQUE VIEW', code: '17170', amount: 1000 },
  { name: 'X-RAY C-SPINE AP', code: '16850', amount: 1000 },
  { name: 'X-RAY C-SPINE AP/LAT', code: '16870', amount: 1000 },
  { name: 'X-RAY C-SPINE B/L OBLIQUE VIEW', code: '22224', amount: 1000 },
  { name: 'X-RAY C-SPINE LAT', code: '16860', amount: 1000 },
  { name: 'X-RAY C-SPINE LAT (EXTENSION/FLEXION)', code: '77733', amount: 1000 },
  { name: 'X-RAY C-SPINE OBLIQUE', code: '16880', amount: 1000 },
  { name: 'X-RAY DORSAL SPINE LAT', code: '16900', amount: 1000 },
  { name: 'X-RAY DORSAL SPINE-AP', code: '16890', amount: 1000 },
  { name: 'X-RAY DORSO LUMBAR SPINE AP', code: '55013', amount: 1000 },
  { name: 'X-RAY DORSO LUMBAR SPINE LAT', code: '11773', amount: 1000 },
  { name: 'X-RAY FINGER AP/LAT', code: '17140', amount: 1000 },
  { name: 'X-RAY HAND WITH WRIST AP/OBLIQUE', code: '17120', amount: 1000 },
  { name: 'X-RAY HIPJOINTS LAT', code: 'XRHJL', amount: 1000 },
  { name: 'X-RAY INVERTOGRAM', code: '11113', amount: 1000 },
  { name: 'X-RAY KUB', code: 'VBNVN', amount: 1000 },
  { name: 'X-RAY L.S. SPINE AP', code: '16910', amount: 1000 },
  { name: 'X-RAY L.S. SPINE AP/LAT', code: 'LSAPL', amount: 1000 },
  { name: 'X-RAY L.S. SPINE LAT', code: '16920', amount: 1000 },
  { name: 'X-RAY LT KNEE WITH LEG AP/LAT', code: '78900', amount: 1000 },
  { name: 'X-RAY LT ANKLE JOINT AP/LAT', code: '99887', amount: 1000 },
  { name: 'X-RAY LT ARM WHOLE LENGTH AP/LAT', code: '33449', amount: 1000 },
  { name: 'X-RAY LT CLAVICLE AP', code: '1853', amount: 1000 },
  { name: 'X-RAY LT CLAVICLE AP', code: 'XLCTA', amount: 1000 },
  { name: 'X-RAY LT ELBOW JOINT AP/LAT', code: '55002', amount: 1000 },
  { name: 'X-RAY LT FOOT AP/OBLIQUE', code: '33441', amount: 1000 },
  { name: 'X-RAY LT FOREARM WHOLE LENGTH AP/LAT', code: '55441', amount: 1000 },
  { name: 'X-RAY LT FOREARM WITH ELBOW AP/LAT', code: '40887', amount: 1000 },
  { name: 'X-RAY LT FOREARM WITH WRIST AP/LAT', code: '44772', amount: 1000 },
  { name: 'X-RAY LT HAND AP/OBLIQUE', code: '55660', amount: 1000 },
  { name: 'X-RAY LT HEEL AXIAL/LATERAL', code: '11119', amount: 1000 },
  { name: 'X-RAY LT HIP WITH THIGH AP/LAT', code: '78534', amount: 1000 },
  { name: 'X-RAY LT KNEE AP/LAT', code: '66445', amount: 1000 },
  { name: 'X-RAY LT KNEE JOINT AP/LAT', code: '37622', amount: 1000 },
  { name: 'X-RAY LT KNEE STANDING AP', code: '11111', amount: 1000 },
  { name: 'X-RAY LT LEG WHOLE LENGTH AP/LAT', code: '33440', amount: 1000 },
  { name: 'X-RAY LT LEG WITH ANKLE AP/LAT', code: '34256', amount: 1000 },
  { name: 'X-RAY LT MASTOID LAT-OBLIQUE VIEW', code: '66331', amount: 1000 },
  { name: 'X-RAY LT PATELLA SKYLINE VIEW AP/LAT', code: '44556', amount: 1000 },
  { name: 'X-RAY LT SCAPULA AP', code: '558', amount: 1000 },
  { name: 'X-RAY LT SCAPULA AP/LAT', code: '99004', amount: 1000 },
  { name: 'X-RAY LT SHOULDER AP', code: '44335', amount: 1000 },
  { name: 'X-RAY LT SHOULDER AP/AXIAL', code: '96532', amount: 1000 },
  { name: 'X-RAY LT SHOULDER WITH ARM AP/LAT', code: '44332', amount: 1000 },
  { name: 'X-RAY LT SI JOINT AP/OBLIQUE', code: '998', amount: 1000 },
  { name: 'X-RAY LT THIGH WITH KNEE AP/LAT', code: '85289', amount: 1000 },
  { name: 'X-RAY LT TM JOINT LAT-OBLIQUE VIEW', code: '11114', amount: 1000 },
  { name: 'X-RAY LT WRIST JOINT AP/LAT', code: '994', amount: 1000 },
  { name: 'X-RAY LT WRIST SCAPHOID VIEW', code: '55667', amount: 1000 },
  { name: 'X-RAY LT. FOOT WITH ANKLE AP/OBLIQUE', code: '11999', amount: 1000 },
  { name: 'X-RAY MANDIBLE B/L (LAT/OBLIQUE)', code: '16810', amount: 1000 },
  { name: 'X-RAY MANDIBLE-AP/ B/L (LAT-OBLIQUE)', code: '16820', amount: 1000 },
  { name: 'X-RAY MAXILLA-AP', code: '16830', amount: 1000 },
  { name: 'X-RAY NASAL BONE-LAT', code: '17220', amount: 1000 },
  { name: 'X-RAY NASOPHARYNX LAT VIEW', code: '88885', amount: 1000 },
  { name: 'X-RAY NECK AP/LAT', code: '17810', amount: 1000 },
  { name: 'X-RAY PELVIS-AP BOTH HIPJOINT', code: '16940', amount: 1000 },
  { name: 'X-RAY PNS OM', code: '16800', amount: 1000 },
  { name: 'X-RAY RT KNEE WITH LEG AP/LAT', code: '16990', amount: 1000 },
  { name: 'X-RAY RT ANKLE JOINT AP/LAT', code: '17010', amount: 1000 },
  { name: 'X-RAY RT ARM WHOLE LENGTH AP/LAT', code: '99221', amount: 1000 },
  { name: 'X-RAY RT CLAVICLE AP', code: '17050', amount: 1000 },
  { name: 'X-RAY RT ELBOW JOINT AP/LAT', code: '17080', amount: 1000 },
  { name: 'X-RAY RT FOOT AP/OBLIQUE', code: '17020', amount: 1000 },
  { name: 'X-RAY RT FOREARM WHOLE LENGTH AP/LAT', code: '99885', amount: 1000 },
  { name: 'X-RAY RT FOREARM WITH ELBOW AP/LAT', code: '17090', amount: 1000 },
  { name: 'X-RAY RT FOREARM WITH WRIST AP/LAT', code: '17100', amount: 1000 },
  { name: 'X-RAY RT HAND AP/OBLIQUE', code: '17130', amount: 1000 },
  { name: 'X-RAY RT HEEL AXIAL/LATERAL', code: '1923', amount: 1000 },
  { name: 'X-RAY RT HIP WITH THIGH AP/LAT', code: '16960', amount: 1000 },
  { name: 'X-RAY RT KNEE AP/LAT', code: '17210', amount: 1000 },
  { name: 'X-RAY RT KNEE JOINT AP/LAT', code: '16980', amount: 1000 },
  { name: 'X-RAY RT KNEE STANDING AP', code: '85858', amount: 1000 },
  { name: 'X-RAY RT LEG WHOLE LENGTH AP/LAT', code: '55440', amount: 1000 },
  { name: 'X-RAY RT LEG WITH ANKLE AP/LAT', code: '17000', amount: 1000 },
  { name: 'X-RAY RT MASTOID LAT-OBLIQUE VIEW', code: '16840', amount: 1000 },
  { name: 'X-RAY RT PATELLA SKYLINE VIEW AP/LAT', code: '88350', amount: 1000 },
  { name: 'X-RAY RT SCAPULA AP', code: '17840', amount: 1000 },
  { name: 'X-RAY RT SCAPULA AP/LAT', code: '17850', amount: 1000 },
  { name: 'X-RAY RT SHOULDER AP', code: '17860', amount: 1000 },
  { name: 'X-RAY RT SHOULDER AP/AXIAL', code: '17040', amount: 1000 },
  { name: 'X-RAY RT SHOULDER WITH ARM AP/LAT', code: '17060', amount: 1000 },
  { name: 'X-RAY RT SI JOINT AP/OBLIQUE', code: '11224', amount: 1000 },
  { name: 'X-RAY RT THIGH WITH KNEE AP/LAT', code: '16970', amount: 1000 },
  { name: 'X-RAY RT TM JOINT LAT-OBLIQUE VIEW', code: '11115', amount: 1000 },
  { name: 'X-RAY RT WRIST JOINT AP/LAT', code: '17110', amount: 1000 },
  { name: 'X-RAY RT WRIST SCAPHOID VIEW', code: '11123', amount: 1000 },
  { name: 'X-RAY RT. FOOT WITH ANKLE AP/OBLIQUE', code: '11132', amount: 1000 },
  { name: 'X-RAY SACRUM AP/LAT', code: '16930', amount: 1000 },
  { name: 'X-RAY SACRUM LAT', code: 'SALAT', amount: 1000 },
  { name: 'X-RAY SKULL AP', code: '16770', amount: 1000 },
  { name: 'X-RAY SKULL AP/LAT', code: '16790', amount: 1000 },
  { name: 'X-RAY SKULL CADWELLS VIEW', code: '99997', amount: 1000 },
  { name: 'X-RAY SKULL LAT', code: '16780', amount: 1000 },
  { name: 'X-RAY SKULL SUBMENTOVERTEX VIEW', code: '99998', amount: 1000 },
  { name: 'X-RAY SKULL WATERS VIEW', code: '99955', amount: 1000 },
  { name: 'X-RAY SOFT TISSUE NECK LAT', code: '18090', amount: 1000 },
  { name: 'X-RAY TOE AP/LAT', code: '17030', amount: 1000 },
  { name: 'XXXXX', code: 'SLCF1', amount: 1500 },
  { name: 'XXXXX', code: 'SLPCT', amount: 1000 },
  { name: 'XXXXXXX', code: 'alpsa', amount: 900 },
  { name: 'xyz', code: '99999', amount: 1000 },
  { name: 'Zeil Neelsen stain, Body fluid', code: '11339', amount: 1500 },
  { name: 'ZINC,serum', code: 'alzin', amount: 1800 },
];
